### ISSUE TITLE
[Feature] Select what coins to auto-sell

### ISSUE THREAD

**Issue by wdl1908** [dtbartle/altcoin-autosell#4]
It would be nice to specify what coins to auto-sell.

I lake to manually trade on certain coins but auto-sell the mined coins.

So specifying a list of coins to sell would be nice.

**Comment by dtbartle** [comment]
I'm hoping to add this feature soon.

**Comment by dtbartle** [comment]
Soon turned out to be really soon :) You can now set the source currencies by setting source_currencies in the config.
